# day objective
## numpy

In [5]:
import numpy as np


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# version
np.__version__

'1.20.3'

In [4]:
# methods
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__sp

In [10]:
# array creation
n1=np.array([1,2,3])
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.itemsize)#memory used by each element
print(n1.dtype)

[1 2 3]
<class 'numpy.ndarray'>
1
4
int32


In [12]:
n1=np.array([1,2,'a'])
print(n1.dtype)
#unicode 11 character datatype

<U11


In [15]:
n1=np.array([[1,2],[3,4]])
print(n1.ndim)

2


In [16]:
n1=np.array([[1,2,3,0],[4,5,6,9],[7,8,9,3]])
print(n1.ndim)
print(n1.shape)

2
(3, 4)


In [18]:
# multi dimensional
n1=np.array([[[1,2],[3,4]]])
print(n1.ndim)

3


# advantades of numpy
-numpy array are more compact than list

-requires less storage space

-executes fast

### numpy methods
- np.arange()
- np.linspace()
- np.ones()
- np.zeros()
- reshape
-statistical methods
- random methods

In [19]:
for i in range(10,20):
    print(i)
    

10
11
12
13
14
15
16
17
18
19


In [20]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [22]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
np.linspace(0,10,20,retstep = True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones([3,2,4],dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros([3,2,4],dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [33]:
a=np.array([[1,2,3,7],[4,5,6,8]])
print(a.shape)
a.reshape(4,2)

(2, 4)


array([[1, 2],
       [3, 7],
       [4, 5],
       [6, 8]])

In [37]:
a1=np.arange(10,30)
len(a1)
a2=a1.reshape(4,5)
print(a2)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


### statistical methods

In [40]:
print(np.max(a2))
print(np.min(a2))
print(np.argmax(a2)) #position of max term
print(np.argmin(a2))
print(np.cumsum(a2))
print(np.mean(a2))
print(np.median(a2))

29
10
19
0
[ 10  21  33  46  60  75  91 108 126 145 165 186 208 231 255 280 306 333
 361 390]
19.5
19.5


In [41]:
print(np.log(10))
print(np.log2(10))
print(np.log10(10))

2.302585092994046
3.321928094887362
1.0


In [43]:
print(np.sin(3.142/3))
print(np.cos(3.142/3))
print(np.tan(3.142/3))

0.8660932868692341
0.4998824046113711
1.732594063883025
