# numpy random methods
## pandas library

In [1]:
import numpy as np

In [2]:
np.random.randint(10)

8

In [3]:
np.random.randint(1,9)

4

In [5]:
np.random.randint(10,20,6)

array([10, 19, 16, 10, 11, 16])

In [16]:
np.random.randint(10,20,[3,2]) # btw no,[rows,colmns]

array([[13, 15],
       [16, 18],
       [19, 10]])

In [6]:
np.random.rand() # random numbers btw 0 and 1

0.056840454122460304

In [7]:
np.random.rand(5)

array([0.01691686, 0.96197291, 0.19100018, 0.03093449, 0.01741682])

In [14]:
np.random.rand(2,4) # row,column

array([[0.98572008, 0.30597946, 0.83384716, 0.75027507],
       [0.11099302, 0.73226938, 0.40309922, 0.79271233]])

In [13]:
np.random.rand(2,4,3) # no of array , row,column

array([[[0.40208157, 0.14515374, 0.81175115],
        [0.81430524, 0.04731455, 0.08477998],
        [0.50035921, 0.89780687, 0.63837147],
        [0.70612254, 0.65372544, 0.37311581]],

       [[0.57084748, 0.0263183 , 0.87548919],
        [0.57809199, 0.85755586, 0.554108  ],
        [0.00768286, 0.0268998 , 0.4628495 ],
        [0.29696787, 0.4344481 , 0.18203902]]])

# pandas

In [17]:
import pandas as pd

In [18]:
pd.__version__

'1.3.4'

In [21]:
## create series using list or tuple
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [22]:
pd.Series((1,2,3,4,5))

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [23]:
a=np.array([1,2,3,4])
pd.Series(a)

0    1
1    2
2    3
3    4
dtype: int32

In [25]:
a={'a':2,'b':3,'c':4}
pd.Series(a)

a    2
b    3
c    4
dtype: int64

In [26]:
pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [28]:
a=[1,2,3,4,5]
pd.DataFrame(a)


0
0  1
1  2
2  3
3  4
4  5

In [29]:
pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['a','b','c'],index=[1,2,3])

a  b  c
1  1  2  3
2  4  5  6
3  7  8  9

In [34]:
a={'a':[1,2],'b':[3,4],'c':[5,6]}
d=pd.DataFrame(a,index=[1,2])
d

a  b  c
1  1  3  5
2  2  4  6

In [37]:
d.index


Int64Index([1, 2], dtype='int64')

In [38]:
d.columns


Index(['a', 'b', 'c'], dtype='object')

In [39]:
d.shape


(2, 3)

In [40]:
d.dtypes

a    int64
b    int64
c    int64
dtype: object

In [43]:
d['b'][1]

3

### indexing
- selecting rows

    - dataframe[startindex:end index]

- selecting colmns
      
      - dataframe[[colmnname1,name2........]]

In [45]:
d[1:2]

a  b  c
2  2  4  6

In [48]:
d[1]

KeyError: 1

In [46]:
d['a']

1    1
2    2
Name: a, dtype: int64

In [47]:
d[['a','c']]

a  c
1  1  5
2  2  6

### iloc and loc
### iloc -acess default index values
### loc - access user defined index values

In [53]:
d.iloc[1]

a    2
b    4
c    6
Name: 2, dtype: int64

In [50]:
d.loc[1]

a    1
b    3
c    5
Name: 1, dtype: int64

In [51]:
d

a  b  c
1  1  3  5
2  2  4  6

In [54]:
d.iloc[1,2]

6

In [55]:
d.loc[2,'c']

6